version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
    - 80:80
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    volumes:
      - ./rails_app:/rails_app
    environment:
      - RAILS_ENV=production
    depends_on:
      - db
    